portfolioapp/about/routes.py
from flask import Blueprint, render_template

from portfolioapp.models import About, Skill

# create a blueprint about
about = Blueprint('about', __name__, template_folder='templates')


@about.route('/about', methods=['GET'])
def index_about():
    """
    Function to render the page

    about_me: model from the database for the about_me page,
    skill_list: model from the database for the skill_list page

    :return: rendered template
    """
    from wsgi import app
    app.logger.info(msg='get started with "about" functions')

    about_me = About.query.get(1)
    app.logger.warning(msg='model loaded "about_me"')

    skill_list = Skill.query.all()
    app.logger.warning(msg='model loaded "skill_list"')

    return render_template('about/about.html',
                           about=about_me,
                           skill_list=skill_list,
                           )

portfolioapp/contact/routes.py
from flask import Blueprint, render_template, request, flash
from flask_mail import Message

from portfolioapp import mail
from portfolioapp.contact.form import ContactForm
from portfolioapp.models import Contact, User

# create a blueprint contact
contact = Blueprint('contact', __name__, template_folder='templates')


@contact.route('/contact', methods=['GET', 'POST'])
def index_contact():
    """
    function for rendering pages, in the case of a post request,
    sending the form by email

    contact: model from the database for the Contact page,
    form: form on page

    :return: rendered template
    """
    from wsgi import app
    app.logger.info(msg='get started with "admin_conntact" functions')

    contact = Contact.query.get(1)
    app.logger.warning(msg='Contact model requested')

    form = ContactForm(request.form)
    app.logger.warning(msg='Getting a form from a request')

    if request.method == 'POST':
        app.logger.warning(msg='Post method')

        if form.validate() == True:
            app.logger.warning(msg='the form is valid, sending a message')
            msg = Message('Yor title text', sender='your email', recipients=[User.query.get(1).email])
            msg.body = f'name: {form.name.data}, phone: {form.phone.data}, email: {form.email.data} ' \
                       f'text: {form.message.data}'
            mail.send(msg)
            flash('The form has been sent, please wait for a response.')
            app.logger.info(msg='letter sent')
        else:
            app.logger.warning(msg='Form filling error')
            flash('Data error! Form not sent!')

    app.logger.info(msg='Get render template')
    return render_template('contact/contact.html', form=form, contact=contact)

portfolioapp/home/routes.py
from flask import Blueprint, render_template

from portfolioapp.models import Home, Photo


home = Blueprint('home', __name__, template_folder='templates')


@home.route('/', methods=['GET'])
def index_home():
    """
    Function to render the page

    home: model from the database for the Home page,
    image: model from the database for the Photo page

    :return: rendered template
    """
    from wsgi import app
    app.logger.info(msg='get started with "index_home" functions')

    home = Home.query.get(1)
    app.logger.warning(msg='model loaded "home"')

    image = Photo.query.all()
    app.logger.warning(msg='model loaded "image"')

    app.logger.info(msg='get render template')
    return render_template('home/index.html', home=home, image_list=image)

portfolioapp/portfolio/routes.py
from flask import Blueprint, render_template
from werkzeug.exceptions import HTTPException

from portfolioapp.models import Portfolio

# create a blueprint portfolio
portfolio = Blueprint('portfolio', __name__, template_folder='templates')


@portfolio.route('/portfolio_<int:pk>', methods=['GET'])
def index_portfolio(pk):
    """
    Function to render the page
        pk: portfolio model primary key

    portfolio: model from the database for the Portfolio page,
    image_list: photos taken from portfolio
    next_portfolio: model from the database for the next Portfolio page,

    :return: rendered template
    """
    from wsgi import app
    app.logger.info(msg='get started with "index_portfolio" functions')
    try:
        portfolio = Portfolio.query.get(pk)
        app.logger.warning(msg='model loaded "portfolio"')
        image_list = [portfolio.image_2, portfolio.image_3,
                     portfolio.image_4, portfolio.image_5, portfolio.image_6,
                     portfolio.image_7, portfolio.image_8, portfolio.image_9, portfolio.image_10]
        app.logger.warning(msg='model loaded "image_list"')
    except AttributeError:
        app.logger.error(msg='Error! Portfolios are not loaded!')
        raise HTTPException('Ошибка! Портфолио не загружены!')

    image_list = [image for image in image_list if image]
    next_portfolio = Portfolio.query.get(pk + 1)
    app.logger.warning(msg='model loaded "next portfolio"')

    app.logger.info(msg='get render template')
    return render_template('portfolio/portfolio.html',
                           portfolio=portfolio,
                           next_portfolio=next_portfolio,
                           pk=pk,
                           image_list=image_list,
                           )

portfolioapp/templates/base.html
<!DOCTYPE HTML>
<html lang="en" class="no-js">

  <head>

      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <meta name="description" content="your text">
    
      <title>Your title</title>

      <!-- ============ Google Fonts ============ -->
      <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

      <!-- CSS -->
      <!-- Flexslider -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/flexslider.css">
      <!-- Font-Awesome 6 PRO-->
      <link rel="stylesheet" href="static/fonts/all.min.css" />
      <!-- LightCase -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/lightcase.css">
      <!-- SlickNav -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/slicknav.min.css">
      <!-- Animate -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/animate.min.css">
      <!-- Bootstrap 5 -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/bootstrap.min.css">
      <!-- Cube Portfolio -->
      <link rel="stylesheet" type="text/css" href="static/css/plugins/cubeportfolio.min.css">
      <!-- Custom styles CSS -->
      <link rel="stylesheet" type="text/css" href="static/css/main.css">
      <!-- Favicon -->
      <link rel="icon" type="image/png" href="static/images/favicon.png">

  </head>
  <body>

<script type='text/javascript'>var words = ["LOADING", "PORTFOLIO", "MODERN", "PHOTOGRAPHER", "Your Text"];</script>

<!-- LOADER TEMPLATE -->
<div class="page-loader">
<div class="text-loader">
  <div class="right">
      <h4 class="randoms"></h4>
      <h1 class="randoms"></h1>
      <h4 class="randoms"></h4>
  </div>
  <div class="left">
      <h4 class="randoms"></h4>
      <h1 class="randoms"></h1>
      <h4 class="randoms"></h4>
  </div>
</div>
</div>
<!-- /LOADER TEMPLATE -->

<!-- ADD THIS CLASS IF YOU WANT STICKY class="sticky"-->            
<header>
  <div class="container">
    <div class="row">
      <div class="col-md-12">

          {% block logo %}
         <!-- logo -->
         <div class="logo">
             <a href="{{ url_for('home.index_home') }}"><img src="static/images/label.png" alt="" width="100px"></a>
         </div>
         <!-- /logo -->
          {% endblock %}

         <nav>

            <div id="rex_menu">
                <ul>
                {% block nav_home %}
                <li class="has-sub">
                    <a href="{{ url_for('home.index_home') }}">
                        <span>Home</span>
                    </a>
                </li>
                {% endblock %}
                {% block nav_portfolio%}
                <li class="has-sub">
                    <a href="{{ url_for('portfolio.index_portfolio', pk=1) }}">
                        <span>Portfolio</span>
                    </a>
                </li>
                {% endblock %}
                {% block nav_contact %}
                <li class="has-sub">
                    <a href="{{ url_for('contact.index_contact') }}">
                        <span>Contact</span>
                    </a>
                </li>
                {% endblock %}
                {% block nav_about%}
                <li class="has-sub">
                    <a href="{{ url_for('about.index_about') }}">
                        <span>About me</span>
                    </a>
                </li>
                {% endblock %}
                </ul>
            </div>

         </nav>
         <!-- /navigation -->
       </div>
     </div>
  </div>
</header>

{% block wrapper %}{% endblock %}

<!-- footer -->
<footer>

    <div class="container">
      <div class="row">
        <div class="col-md-12">

      <!-- social icons -->
      <div class="social-icons">
        <ul>

          <li><a href="" target="_blank"><i class="fa-brands fa-vk"></i></a></li>
          <li><a href="" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
          <li><a href="" target="_blank"><i class="fa-brands fa-google"></i></a></li>
        </ul>
      </div>
      <!-- /social icons -->  

      <!-- copyright -->
      <div class="copyright">
          Your text © 2023.<a href='https://github.com/Ser-Alex' target='_blank'>Design & Coded by SerAlex.</a>
      </div>
      <!-- /copyright -->

     </div>
    </div>
  </div>

</footer>
<!-- /footer -->
  {% block javascript %}
    <!-- Javascript files -->
    <!-- jQuery -->
    <script src="static/js/plugins/jquery-1.12.4.min.js"></script>
    <!-- Modernizr -->
    <script src="static/js/plugins/modernizr.js"></script>
    <!-- jQuery.appear -->
    <script src="static/js/plugins/jquery.appear.js"></script>
    <!-- Lettering -->
    <script src="static/js/plugins/lettering.js"></script>
    <!-- Textillate -->
    <script src="static/js/plugins/textillate.js"></script>
    <!-- Wow -->
    <script src="static/js/plugins/wow.js"></script>
    <!-- Jarallax -->
    <script src="static/js/plugins/jarallax.js"></script>
    <!-- Lightcase -->
    <script src="static/js/plugins/lightcase.js"></script>
    <!-- Skills bar -->
    <script src="static/js/plugins/skills-bar.js"></script>
    <!-- Slick Nav -->
    <script src="static/js/plugins/slick-nav.js"></script>
    <!-- Flex Slider -->
    <script src="static/js/plugins/flexslider.js"></script>
    <!-- Images Loaded -->
    <script src="static/js/plugins/images-loaded.js"></script>
    <!-- Isotope -->
    <script src="static/js/plugins/isotope.js"></script>
    <!-- Sticky Plugin -->
    <script src="static/js/plugins/jquery.sticky.js"></script>
    <!-- Cube Portfolio -->
    <script src="static/js/plugins/jquery.cubeportfolio.min.js"></script>
    <!-- Google map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAV1KS10sb3O462XosfZTKohHJwi6C0joo"></script>
    <!-- Custom -->
    <script src="static/js/main.js"></script>
  {% endblock %}

    
</body>
</html>

portfolioapp/templates/index.html
<html>
    <body>
        <div>
            <a href="{{ url_for('admin.index') }}">Go to admin!</a>
        </div>
    </body>
</html>

portfolioapp/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="btn" href="{{ url_for('admin.logout_view') }}">Log out</a>
  </div>
</div>
{% endif %}
{% endblock %}